
version: '3.4'

services:
  productservice:
    build:
      context: ./Services/ProductService
    ports:
      - "5001:80"

  orderservice:
    build:
      context: ./Services/OrderService
    ports:
      - "5002:80"

  gatewayservice:
    build:
      context: ./Services/GatewayService
    ports:
      - "5000:80"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"